### Get user by usernmae
GET http://{{host}}:{{port}}/users/Jerry


### Create user
POST http://{{host}}:{{port}}/users
Content-Type: application/json

{
  "username": "Jerry",
  "password": "123456",
  "full_name": "Ki",
  "email": "jerry@email.com"
}

### Create transfer
POST http://{{host}}:{{port}}/transfers
Content-Type: application/json

{
  "from_account_id": 1,
  "to_account_id": 2,
  "amount": 12,
  "currency": "EUR"
}

### List accounts
GET http://{{host}}:{{port}}/accounts?page=100&page_size=5


### Get account by id
GET http://{{host}}:{{port}}/accounts/462


### Create account
POST http://{{host}}:{{port}}/accounts
Content-Type: application/json

{
  "owner": "Tom",
  "currency": "USD"
}



