name: ci-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRE_DB: backend
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retires 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.2
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run migration
        run: migrate -path db/migration -database "postgresql://root:root@localhost:5433/backend?sslmode=disable" -verbose up

      - name: Test
        run: go test -v -cover ./...
